// SvelteTest/src/components/homePage.svelte
<script>
    import { onMount } from 'svelte';
    import miniBlogService from '../lib/miniBlogService';

    let posts = [];
    let newPost = {
        title: '',
        content: '',
        authorUsername: ''
    };
    let postToUpdate = {
        title: '',
        content: '',
        authorUsername: ''
    };

    let selectedPostId = null; // To track the post being updated

    onMount(() => {
        getPosts();
    })

    async function getPosts() {
        try {
            const res = await miniBlogService.getAllPosts();
            posts = res.data; 

        } catch (error) {
            console.error('Kunde inte hämta inlägg:', error);
        }
    }

    async function createPost() {
        try {
            await miniBlogService.createPost(newPost);
            newPost = {
                title: '',
                content: '',
                authorUsername: ''
            }
            await getPosts(); // Refresh the posts after creating a new one
        } catch (error) {
            console.error('Kunde inte skapa inlägg:', error);
        }

    }

    async function editPost(post) {
        newPost = { ...post }; // Populate the form with the selected post's data
        selectedPostId = post.id; // Set the ID of the post to be updated
    }

    async function updatePost() {
        if(!selectedPostId) {
            alert('Ingen post vald för uppdatering!');
            return;
        } // Ensure a post is selected for updating

        try {
            await miniBlogService.updatePost(selectedPostId, newPost);
            newPost = {
                title: '',
                content: '',
                authorUsername: ''
            }
            selectedPostId = null; // Reset the selected post ID after updating
            await getPosts(); // Refresh the posts after updating
        } catch (error) {
            console.error('Kunde inte uppdatera inlägg:', error);
        }
    }

    async function deletePost(id) {
       miniBlogService.deletePost(id)
            .then(() => {
                posts = posts.filter(post => post.id !== id);
            })
            .catch(error => {
                console.error('Kunde inte ta bort inlägg:', error);
            });
    }


</script>


<div>
    <form on:submit|preventDefault={selectedPostId ? updatePost : createPost}>
        <h2>{selectedPostId ? 'Uppdatera inlägg:' : 'Skapa inlägg:'}</h2>
        <input type="text" bind:value={newPost.title} placeholder="Titel" required>
        <textarea placeholder="Content" bind:value={newPost.content} required></textarea>
        <input type="text" bind:value={newPost.authorUsername} required>
        <button type="submit">{selectedPostId ? 'Update post' : 'Create Post'}</button>
    </form>
    
    

    <ul>
        {#each posts as post }
            <li>
                <h2>{post.title}</h2>
                <p>{post.content}</p>
                <small>by: {post.authorUsername}</small> <br>
                <button on:click={() => editPost(post)}>Update</button>
                <button on:click={() => deletePost(post.id)} disabled={selectedPostId !== null}>Delete</button>
            </li>
            
        {/each}
    </ul>
</div>

// VueTest/vuetest/src/components/homePage.vue
<template>
    <form @submit.prevent="selectedPostId ? updatePost() : createPost()">
        <h2>{{ selectedPostId ? 'Update post:' : 'Create post:' }}</h2>
        <label for="Title">Title</label>
        <input type="text" id="Title" v-model="newPost.title" required>

        <label for="Content">Content</label>
        <textarea type="text" id="Content" v-model="newPost.content" required></textarea>

        <label for="authorUsername">Username</label>
        <input type="text" id="authorUsername" v-model="newPost.authorUsername" required>

        <button type="submit">{{ selectedPostId ? 'Update Post' : 'Create Post' }}</button>
    </form>

    <div v-for="post in posts" :key="post.id">
        <h3>{{ post.title }}</h3>
        <p>{{ post.content }}</p>
        <small>Skapad av: {{ post.authorUsername }}</small>
        <small>Skapad: {{ post.createdAt }}</small>
        <small>senast uppdaterad: {{ post.updatedAt }}</small>

        <button @click="deletePost(post.id)" :disabled="selectedPostId !== null">Delete</button>
        <button @click="editPost(post)">Update</button>
    </div>
    
</template>

<script>
import miniBlogService from '../Services/miniBlogService.js';



export default {
    name: 'AppHomePage',
    data(){
        return {
            posts: [],
            newPost: {
                title: '',
                content: '',
                authorUsername: ''
            },
            postToUpdate: {
                title: '',
                content: '',
                authorUsername: ''
            },
            selectedPostId: null, // ID för det inlägg som ska uppdateras
        }
    }, 
    mounted() {
        this.getPosts(); //körs när komponenten laddas
    },
    methods: {
        getPosts() {
            miniBlogService.getPosts()
                .then(response => {
                    this.posts = response.data; //sätter posts till svaret från servern
                })
                .catch(error => {
                    console.error("Error fetching posts:", error);
                });
        }, 

        createPost() {
            miniBlogService.createPost(this.newPost)
                .then(() => {
                    this.newPost = { title: '', content: '', authorUsername: '' }; //rensar formuläret
                    this.getPosts(); //hämtar inläggen igen för att uppdatera listan
                })
        },

        editPost(post) {
            this.newPost = {...post}; //kopierar inlägget som ska uppdateras till formuläret
            this.selectedPostId = post.id; //sätter ID för det inlägg som ska uppdateras
        },

        updatePost() {
            if(!this.selectedPostId) {
                alert("Ingen post vald för uppdatering.");
                return;
            }

            miniBlogService.updatePost(this.selectedPostId, this.newPost) //skickar ID och det nya inlägget till servern
                .then(() => {
                    this.newPost = { title: '', content: '', authorUsername: '' }; //rensar formuläret
                    this.selectedPostId = null; //rensar ID för det inlägg som ska uppdateras
                    this.getPosts(); //hämtar inläggen igen för att uppdatera listan
                })
                .catch(error => {
                    console.error("error updating post:", error)
                })
        }, 

        deletePost(id) {
            miniBlogService.deletePost(id)
                .then(() => {
                    this.getPosts(); //hämtar inläggen igen för att uppdatera listan
                })
                .catch(error => {
                    console.error("Error deleting post:", error);
                });
        }

        
    }
};
</script>

<style scoped>

</style>
