// VueTest/vuetest/src/components/homePage.vue
<template>
    <form @submit.prevent="createPost()">
        <label for="Title">Title</label>
        <input type="text" id="Title" v-model="newPost.title" required>

        <label for="Content">Content</label>
        <textarea type="text" id="Content" v-model="newPost.content" required></textarea>

        <label for="authorUsername">Username</label>
        <input type="text" id="authorUsername" v-model="newPost.authorUsername" required>

        <button type="submit">Create post</button>
    </form>

    <div v-for="post in posts" :key="post.id">
        <h3>{{ post.title }}</h3>
        <p>{{ post.content }}</p>
        <small>Skapad av: {{ post.authorUsername }}</small>
        <small>Skapad: {{ post.createdAt }}</small>
        <small>senast uppdaterad: {{ post.updatedAt }}</small>

        <button @click="deletePost(post.id)">Delete</button>
        <button @click="updatePost(post.id)">Update</button>
    </div>
    
</template>

<script>
import miniBlogService from '../Services/miniBlogService.js';



export default {
    name: 'AppHomePage',
    data(){
        return {
            posts: [],
            newPost: {
                title: '',
                content: '',
                authorUsername: ''
            },
            selectedPostId: null, // ID för det inlägg som ska uppdateras
        }
    }, 
    mounted() {
        this.getPosts(); //körs när komponenten laddas
    },
    methods: {
        getPosts() {
            miniBlogService.getPosts()
                .then(response => {
                    this.posts = response.data; //sätter posts till svaret från servern
                })
                .catch(error => {
                    console.error("Error fetching posts:", error);
                });
        }, 

        createPost() {
            miniBlogService.createPost(this.newPost)
                .then(() => {
                    this.newPost = { title: '', content: '', authorUsername: '' }; //rensar formuläret
                    this.getPosts(); //hämtar inläggen igen för att uppdatera listan
                })
        },

        updatePost(id) {
            miniBlogService.updatePost(id, this.newPost)
                .then(() => {
                    this.newPost = { title: '', content: '', authorUsername: '' }; //rensar formuläret
                    this.getPosts(); //hämtar inläggen igen för att uppdatera listan
                })
                .catch(error => {
                    console.error("error updating post:", error)
                })
        }, 

        deletePost(id) {
            miniBlogService.deletePost(id)
                .then(() => {
                    this.getPosts(); //hämtar inläggen igen för att uppdatera listan
                })
                .catch(error => {
                    console.error("Error deleting post:", error);
                });
        }

        
    }
};
</script>

<style scoped>

</style>

// AngularTest/angularTest/src/app/Components/home-page/home-page.component.ts
import { Component } from '@angular/core';
import { Post } from '../../Models/miniblog.model';
import { MiniblogService } from '../../miniBlogg.service';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';

@Component({
  selector: 'app-home-page',
  imports: [CommonModule, FormsModule],
  standalone: true,
  templateUrl: './home-page.component.html',
  styleUrls: ['./home-page.component.css']
})
export class HomePageComponent {
  post: Post[] = [];
  newPost: Post = {title: '', content: '', authorUsername: '', createdAt: new Date(), updatedAt: new Date()};
  postToUpdate: Post = {title: '', content: '', authorUsername: '', createdAt: new Date(), updatedAt: new Date()};
  selectedPostId: number | null = null;

  constructor(private miniblogService: MiniblogService) { } 

  ngOnInit(): void {
    this.loadPosts();
  }

  loadPosts(): void {
    this.miniblogService.GetAllPosts().subscribe(posts => {
      this.post = posts; 
    });
  }

  createPost(): void {
    this.miniblogService.CreatePost(this.newPost).subscribe(post => {
      this.post.push(post);
      this.newPost = {title: '', content: '', authorUsername: '', createdAt: new Date(), updatedAt: new Date()};

    })
  }

  updatePost(): void {
    if(this.selectedPostId !== null) {
      const originalPost = this.post.find(p => p.id === this.selectedPostId);
      if(!originalPost) return;

      const updatedPost: Post = {
        ...this.postToUpdate,
        id: this.selectedPostId,
        createdAt: originalPost.createdAt,
        updatedAt: new Date()
      };

      this.miniblogService.UpdatePost(updatedPost, this.selectedPostId).subscribe(() => {
        const index = this.post.findIndex(p => p.id === this.selectedPostId);
        if(index !== -1) {
          this.post[index] = updatedPost;
        }
        this.selectedPostId = null;
        this.postToUpdate = {title: '', content: '', authorUsername: '', createdAt: new Date(), updatedAt: new Date()};
      })
    }
  }

  deletePost(id: number): void {
    this.miniblogService.DeletePost(id).subscribe(() => {
      this.post = this.post.filter(p => p.id !== id);
    })
  }

  selectPostToUpdate(id: number): void {
    const post = this.post.find(p => p.id === id);
    if(post) {
      this.selectedPostId = id;
      this.postToUpdate = {
        ...post,
        updatedAt: new Date()
      };
    }
  }

  


}

<h3>Do your first post or read others: </h3>

<h2>Skapa nytt inlägg</h2>
<form (ngSubmit)="createPost()">
    <label for="Title">Title</label>
    <input type="text" name="Title" id="Title" [(ngModel)]="newPost.title" required>

    <label for="Content">Content</label>
    <textarea name="content" id="Content" [(ngModel)]="newPost.content" required=""></textarea>

    <label for="username">Username</label>
    <input type="text" name="authorUsername" id="username" [(ngModel)]="newPost.authorUsername" required>

    <button type="submit">Create post</button>
</form>

<hr />

<h2>All inlägg</h2>
<div *ngFor="let p of post">
    <h3>{{p.title}}</h3>
    <p>{{p.content}}</p>
    <small>skriven av: {{p.authorUsername}}</small> <br />
    <small>Skapad: {{p.createdAt | date:'short'}}</small> <br/>
    <small>Senast uppdaterad: {{p.updatedAt | date:'short'}}</small> <br />

    <button (click)="selectPostToUpdate(p.id!)">Redigera</button>
    <button (click)="deletePost(p.id!)">Ta bort</button>

    <hr />
</div>

<div *ngIf="selectedPostId !== null">
    <h2>Redigera inlägg</h2>
    <form (ngSubmit)="updatePost()">
        <label for="updateTitle">Title</label>
        <input type="text" [(ngModel)]="postToUpdate.title" name="updateTitle" id="updateTitle" required>

        <label for="updateContent">Content</label>
        <textarea name="updateContent" id="updateContent" [(ngModel)]="postToUpdate.content" required=""></textarea>

        <label for="updateAuthorUsername">Username</label>
        <input type="text" [(ngModel)]="postToUpdate.authorUsername" name="updateAuthorUsername" id="updateAuthorUsername" required>

        <button type="submit">Update</button>
        <button type="button" (click)="selectedPostId = null">Avbryt</button>
    </form>


</div>
